-- ========================================
-- PROCEDIMIENTOS ALMACENADOS
-- ========================================

-- PAQUETE PRODUCTOS INICIO
CREATE OR REPLACE PACKAGE COSMETICDEV.PKG_PRODUCTOS
AS
	-- GUARDAR PRODUCTO
    PROCEDURE SP_INSERT_PRODUCTO(
        PROD_ID_CATEGORIA IN COSMETICDEV.TA_PRODUCTOS.ID_CATEGORIA%TYPE,
        PROD_ID_MARCA 	  IN COSMETICDEV.TA_PRODUCTOS.ID_MARCA%TYPE,
        PROD_ID_PROVEEDOR IN COSMETICDEV.TA_PRODUCTOS.ID_PROVEEDOR%TYPE,
        PROD_DESCRIPCION  IN COSMETICDEV.TA_PRODUCTOS.DESCRIPCION%TYPE,
        PROD_CODIGO       IN COSMETICDEV.TA_PRODUCTOS.CODIGO%TYPE,
        PROD_NOMBRE       IN COSMETICDEV.TA_PRODUCTOS.NOMBRE%TYPE,
        PROD_PRECIO       IN COSMETICDEV.TA_PRODUCTOS.PRECIO%TYPE,
        PROD_PRECIO_COSTO IN COSMETICDEV.TA_PRODUCTOS.PRECIO_COSTO%TYPE,
        PROD_STOCK        IN COSMETICDEV.TA_INVENTARIO.STOCK%TYPE,
        PROD_RESULTADO    OUT NUMBER,
     	PROD_MENSAJE      OUT VARCHAR2
    );
    
    -- ACTUALIZAR PRODUCTO
    PROCEDURE SP_UPDATE_PRODUCTO(
        PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        PROD_NOMBRE      IN COSMETICDEV.TA_PRODUCTOS.NOMBRE%TYPE,
        PROD_PRECIO      IN COSMETICDEV.TA_HISTORIAL_PRECIOS.PRECIO_NUEVO%TYPE,
        PROD_DESCRIPCION IN COSMETICDEV.TA_PRODUCTOS.DESCRIPCION%TYPE,
        PROD_ESTADO      IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        PROD_MOTIVO      IN COSMETICDEV.TA_HISTORIAL_PRECIOS.MOTIVO%TYPE,
        PROD_RESULTADO   OUT NUMBER,
     	PROD_MENSAJE     OUT VARCHAR2
    );
    
    -- ELIMINAR PRODUCTO - ELIMINACIÓN LÓGICA
    PROCEDURE SP_DELETE_PRODUCTO(
        PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        PROD_ESTADO      IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        PROD_RESULTADO   OUT NUMBER,
     	PROD_MENSAJE     OUT VARCHAR2
    );
    
    -- OBTENER PRODUCTO POR ID
    PROCEDURE SP_GET_PRODUCTO(
        PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        PROD_CURSOR      OUT SYS_REFCURSOR
    );
    
    -- OBTENER TODOS LOS PRODUCTOS
    PROCEDURE SP_OBTENER_PRODUCTOS(
    	PROD_ESTADO IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        PROD_CURSOR OUT SYS_REFCURSOR
    );
   
END PKG_PRODUCTOS;

CREATE OR REPLACE PACKAGE BODY COSMETICDEV.PKG_PRODUCTOS
AS
	-- GUARDAR PRODUCTO
    PROCEDURE SP_INSERT_PRODUCTO(
        PROD_ID_CATEGORIA IN COSMETICDEV.TA_PRODUCTOS.ID_CATEGORIA%TYPE,
        PROD_ID_MARCA 	  IN COSMETICDEV.TA_PRODUCTOS.ID_MARCA%TYPE,
        PROD_ID_PROVEEDOR IN COSMETICDEV.TA_PRODUCTOS.ID_PROVEEDOR%TYPE,
        PROD_DESCRIPCION  IN COSMETICDEV.TA_PRODUCTOS.DESCRIPCION%TYPE,
        PROD_CODIGO       IN COSMETICDEV.TA_PRODUCTOS.CODIGO%TYPE,
        PROD_NOMBRE       IN COSMETICDEV.TA_PRODUCTOS.NOMBRE%TYPE,
        PROD_PRECIO       IN COSMETICDEV.TA_PRODUCTOS.PRECIO%TYPE,
        PROD_PRECIO_COSTO IN COSMETICDEV.TA_PRODUCTOS.PRECIO_COSTO%TYPE,
        PROD_STOCK        IN COSMETICDEV.TA_INVENTARIO.STOCK%TYPE,
        PROD_RESULTADO    OUT NUMBER,
     	PROD_MENSAJE      OUT VARCHAR2
    ) 
    AS
        V_ID_PRODUCTO NUMBER;
    BEGIN
        INSERT INTO TA_PRODUCTOS 
            (ID_CATEGORIA, ID_MARCA, ID_PROVEEDOR, DESCRIPCION, CODIGO, NOMBRE, PRECIO, PRECIO_COSTO, ESTADO, USUARIO_ACTUALIZACION)
        VALUES 
            (PROD_ID_CATEGORIA, PROD_ID_MARCA, PROD_ID_PROVEEDOR, PROD_DESCRIPCION, PROD_CODIGO, PROD_NOMBRE, PROD_PRECIO, PROD_PRECIO_COSTO, 'ACTIVO', USER)
        
            RETURNING ID_PRODUCTO INTO V_ID_PRODUCTO;

        INSERT INTO TA_INVENTARIO (ID_PRODUCTO, STOCK, STOCK_MIN)
        VALUES (V_ID_PRODUCTO, PROD_STOCK, PROD_STOCK * 0.2); -- Stock mínimo al 20%

        COMMIT;
        
    END SP_INSERT_PRODUCTO;
    
     -- ACTUALIZAR PRODUCTO
    PROCEDURE SP_UPDATE_PRODUCTO(
        PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        PROD_NOMBRE      IN COSMETICDEV.TA_PRODUCTOS.NOMBRE%TYPE,
        PROD_PRECIO      IN COSMETICDEV.TA_HISTORIAL_PRECIOS.PRECIO_NUEVO%TYPE,
        PROD_DESCRIPCION IN COSMETICDEV.TA_PRODUCTOS.DESCRIPCION%TYPE,
        PROD_ESTADO      IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        PROD_MOTIVO      IN COSMETICDEV.TA_HISTORIAL_PRECIOS.MOTIVO%TYPE,
        PROD_RESULTADO   OUT NUMBER,
     	PROD_MENSAJE     OUT VARCHAR2
    ) 
    AS
        V_PRECIO_ANTERIOR NUMBER;
    BEGIN
        -- Guardar precio anterior en historial
        SELECT PRECIO INTO V_PRECIO_ANTERIOR FROM TA_PRODUCTOS WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;
        
        IF V_PRECIO_ANTERIOR != PROD_PRECIO THEN
            INSERT INTO TA_HISTORIAL_PRECIOS 
                (ID_PRODUCTO, PRECIO_ANTERIOR, PRECIO_NUEVO, USUARIO_CAMBIO, MOTIVO)
            VALUES 
                (PROD_ID_PRODUCTO, V_PRECIO_ANTERIOR, PROD_PRECIO, USER, PROD_MOTIVO);
        END IF;
        
        UPDATE TA_PRODUCTOS SET NOMBRE = PROD_NOMBRE, PRECIO = PROD_PRECIO, DESCRIPCION = PROD_DESCRIPCION, ESTADO = PROD_ESTADO, 
           FECHA_ACTUALIZACION = SYSDATE, USUARIO_ACTUALIZACION = USER
        WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;

        COMMIT;
    END SP_UPDATE_PRODUCTO;
    
   -- ELIMINAR PRODUCTO - ELIMINACIÓN LÓGICA     
   PROCEDURE SP_DELETE_PRODUCTO(
        	PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        	PROD_ESTADO      IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        	PROD_RESULTADO   OUT NUMBER,
     		PROD_MENSAJE     OUT VARCHAR2
        ) 
    AS
    BEGIN
        UPDATE TA_PRODUCTOS SET ESTADO = PROD_ESTADO, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;

        COMMIT;
    END SP_DELETE_PRODUCTO;    
    
    -- OBTENER PRODUCTO POR ID
    PROCEDURE SP_GET_PRODUCTO(
        PROD_ID_PRODUCTO IN COSMETICDEV.TA_PRODUCTOS.ID_PRODUCTO%TYPE,
        PROD_CURSOR      OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN PROD_CURSOR FOR
            SELECT P.ID_PRODUCTO, P.NOMBRE, P.DESCRIPCION, P.CODIGO, P.PRECIO, P.PRECIO_COSTO,
                P.ESTADO, C.NOMBRE AS CATEGORIA, M.NOMBRE AS MARCA, 
                PV.NOMBRE AS PROVEEDOR, I.STOCK, I.STOCK_MIN
            FROM TA_PRODUCTOS P
            LEFT JOIN TA_CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
            LEFT JOIN TA_MARCAS M ON P.ID_MARCA = M.ID_MARCA
            LEFT JOIN TA_PROVEEDORES PV ON P.ID_PROVEEDOR = PV.ID_PROVEEDOR
            LEFT JOIN TA_INVENTARIO I ON P.ID_PRODUCTO = I.ID_PRODUCTO
            WHERE P.ID_PRODUCTO = PROD_ID_PRODUCTO;
    
    END SP_GET_PRODUCTO;
        
    
    -- OBTENER TODOS LOS PRODUCTOS
    PROCEDURE SP_OBTENER_PRODUCTOS(
    	PROD_ESTADO IN COSMETICDEV.TA_PRODUCTOS.ESTADO%TYPE,
        PROD_CURSOR OUT SYS_REFCURSOR
    	) 
    AS
    BEGIN
        OPEN PROD_CURSOR FOR
            SELECT 
                P.ID_PRODUCTO, P.NOMBRE, P.DESCRIPCION, P.CODIGO, P.PRECIO, P.PRECIO_COSTO,
                P.ESTADO, C.NOMBRE AS CATEGORIA, M.NOMBRE AS MARCA, 
                PV.NOMBRE AS PROVEEDOR, I.STOCK, I.STOCK_MIN
            FROM TA_PRODUCTOS P
            LEFT JOIN TA_CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
            LEFT JOIN TA_MARCAS M ON P.ID_MARCA = M.ID_MARCA
            LEFT JOIN TA_PROVEEDORES PV ON P.ID_PROVEEDOR = PV.ID_PROVEEDOR
            LEFT JOIN TA_INVENTARIO I ON P.ID_PRODUCTO = I.ID_PRODUCTO
            WHERE P.ESTADO = PROD_ESTADO
            ORDER BY P.ID_PRODUCTO;
    END SP_OBTENER_PRODUCTOS;
    
END PKG_PRODUCTOS;
--PAQUETE PRODUCTOS FIN