-- ========================================
-- PROCEDIMIENTOS ALMACENADOS
-- ========================================
-- PAQUETE USUARIO INICIO
CREATE OR REPLACE PACKAGE PKG_USUARIOS AS
    -- CREAR USUARIO
    PROCEDURE CREAR_USUARIO(
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_USUARIO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_ID_ROL IN NUMBER
    );
    
    -- ACTUALIZAR DATOS PERSONALES
    PROCEDURE UPDATE_USUARIO(
        USER_ID IN NUMBER,
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2
    );
    
    -- ACTUALIZAR ACCESO USUARIO
    PROCEDURE UPDATE_USUARIO_ACCESO(
        USER_ID IN NUMBER,
        USER_USUARIO IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_ESTADO IN VARCHAR2
    );
    
    -- LISTAR TODOS LOS USUARIOS
    PROCEDURE LISTAR_USUARIOS(
        USER_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR USUARIO POR ID
    PROCEDURE LISTAR_USUARIOS_ID(
        USER_ID IN NUMBER,
        USER_CURSOR OUT SYS_REFCURSOR
    );
    
    -- CAMBIAR ROL DE USUARIO
    PROCEDURE CAMBIAR_ROL_USUARIO(
        USER_ID IN NUMBER,
        USER_ID_ROL IN NUMBER
    );
    
END PKG_USUARIOS;

CREATE OR REPLACE PACKAGE BODY PKG_USUARIOS AS

    -- CREAR USUARIO
    PROCEDURE CREAR_USUARIO(
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_USUARIO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_ID_ROL IN NUMBER,
        USER_MODIFICACION IN VARCHAR2
    ) 
    AS
    BEGIN
        INSERT INTO TA_USUARIOS 
            (NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NACIMIENTO, TELEFONO, USUARIO, EMAIL, PASSWORD_HASH, ESTADO, ID_ROL, USUARIO_ACTUALIZACION)
        VALUES 
            (USER_NOMBRE, USER_PATERNO, USER_MATERNO, USER_FECHA_NAC, USER_TELEFONO, USER_USUARIO, USER_EMAIL, USER_PASSWORD, 'ACTIVO', USER_ID_ROL, USER);
        
        COMMIT;
    END CREAR_USUARIO;

    -- ACTUALIZAR DATOS PERSONALES
    PROCEDURE UPDATE_USUARIO(
        USER_ID IN NUMBER,
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2
    ) 
    AS
    BEGIN
        UPDATE TA_USUARIOS SET NOMBRE = USER_NOMBRE, AP_PATERNO = USER_PATERNO, AP_MATERNO = USER_MATERNO, FECHA_NACIMIENTO = USER_FECHA_NAC, 
            TELEFONO = USER_TELEFONO, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END UPDATE_USUARIO;

        -- ACTUALIZAR ACCESO USUARIO
    PROCEDURE UPDATE_USUARIO_ACCESO(
        USER_ID IN NUMBER,
        USER_USUARIO IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_ESTADO IN VARCHAR2
    )
    AS
    BEGIN
        UPDATE TA_USUARIOS SET USUARIO = USER_USUARIO, PASSWORD_HASH = USER_PASSWORD, ESTADO = USER_ESTADO, 
        	EMAIL = USER_EMAIL, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END UPDATE_USUARIO_ACCESO;

           -- LISTAR TODOS LOS USUARIOS
    PROCEDURE LISTAR_USUARIOS(
        USER_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN USER_CURSOR FOR
            SELECT U.ID_USUARIO, U.NOMBRE, U.AP_PATERNO, U.AP_MATERNO, U.FECHA_NACIMIENTO, U.TELEFONO, U.EMAIL, U.USUARIO,
                R.NOMBRE_ROL, U.ESTADO, U.FECHA_CREACION
            FROM TA_USUARIOS U
            LEFT JOIN TA_ROLES R ON U.ID_ROL = R.ID_ROL
            ORDER BY U.ID_USUARIO;
    END LISTAR_USUARIOS;
    
    -- LISTAR USUARIO POR ID
    PROCEDURE LISTAR_USUARIOS_ID(
        USER_ID IN NUMBER,
        USER_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN USER_CURSOR FOR
            SELECT 
                U.ID_USUARIO, U.NOMBRE, U.AP_PATERNO, U.AP_MATERNO, U.FECHA_NACIMIENTO, U.TELEFONO, U.EMAIL, U.USUARIO, 
                R.NOMBRE_ROL, U.ESTADO, U.FECHA_CREACION
            FROM TA_USUARIOS U
            LEFT JOIN TA_ROLES R ON U.ID_ROL = R.ID_ROL
            WHERE U.ID_USUARIO = USER_ID;
    END LISTAR_USUARIOS_ID;
    
    -- CAMBIAR ROL DE USUARIO
    PROCEDURE CAMBIAR_ROL_USUARIO(
        USER_ID IN NUMBER,
        USER_ID_ROL IN NUMBER
    )
    AS
    BEGIN
        UPDATE TA_USUARIOS SET ID_ROL = USER_ID_ROL, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END CAMBIAR_ROL_USUARIO;

END PKG_USUARIOS;
--PAQUETE USUARIO FINAL