-- ========================================
-- PROCEDIMIENTOS ALMACENADOS
-- ========================================
-- PAQUETE BENEFICIOS INICIO
CREATE OR REPLACE PACKAGE PKG_BENEFICIOS AS

    PROCEDURE SP_REGISTRAR_BENEFICIO(
        PROD_NOMBRE IN VARCHAR2,
        PROD_DESCRIPCION IN VARCHAR2
    );

    -- AGREGAR BENEFICIO A PRODUCTO
    PROCEDURE SP_AGREGAR_BENEFICIO_PROD(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_ID_BENEFICIO IN NUMBER
    );

     -- ELIMINAR BENEFICIO DE PRODUCTO
    PROCEDURE SP_ELIMINAR_BENEFICIO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_ID_BENEFICIO IN NUMBER
    );

    -- OBTENER BENEFICIOS POR USUARIO
    PROCEDURE OBTENER_BENEFICIOS_USUARIO(
        P_ID_USUARIO IN NUMBER,
        BENEFICIOS_CURSOR OUT SYS_REFCURSOR
    );
    
    -- APLICAR BENEFICIO A USUARIO
    PROCEDURE APLICAR_BENEFICIO_USUARIO(
        P_ID_USUARIO IN NUMBER,
        P_ID_BENEFICIO IN NUMBER
    );
    
    -- LISTAR BENEFICIOS DISPONIBLES
    PROCEDURE LISTAR_BENEFICIOS_DISPONIBLES(
        BENEFICIOS_CURSOR OUT SYS_REFCURSOR
    );
    
END PKG_BENEFICIOS;
