-- ========================================
-- PAQUETE PARA MANEJO DE REGALOS
-- ========================================

CREATE OR REPLACE PACKAGE PKG_REGALOS AS
    -- CREAR REGALO
    PROCEDURE SP_CREAR_REGALO(
        P_NOMBRE IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2,
        P_VALOR_EQUIVALENTE IN NUMBER,
        P_STOCK IN NUMBER
    );
    
    -- ASIGNAR REGALO A CLIENTE
    PROCEDURE SP_ASIGNAR_REGALO_CLIENTE(
        P_ID_USUARIO IN NUMBER,
        P_ID_REGALO IN NUMBER,
        P_FECHA_VENCIMIENTO IN DATE DEFAULT NULL,
        P_ID_VENTA IN NUMBER DEFAULT NULL
    );
    
    -- CANJEAR REGALO
    PROCEDURE SP_CANJEAR_REGALO(
        P_ID_CLIENTE_REGALO IN NUMBER
    );
    
    -- LISTAR REGALOS DISPONIBLES DEL CLIENTE
    PROCEDURE SP_LISTAR_REGALOS_CLIENTE(
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR TODOS LOS REGALOS
    PROCEDURE SP_LISTAR_REGALOS(
        P_CURSOR OUT SYS_REFCURSOR
    );
    
END PKG_REGALOS;

CREATE OR REPLACE PACKAGE BODY PKG_REGALOS AS

    -- CREAR REGALO
    PROCEDURE SP_CREAR_REGALO(
        P_NOMBRE IN VARCHAR2,
        P_DESCRIPCION IN VARCHAR2,
        P_VALOR_EQUIVALENTE IN NUMBER,
        P_STOCK IN NUMBER
    ) 
    AS
    BEGIN
        INSERT INTO TA_REGALOS (NOMBRE, DESCRIPCION, VALOR_EQUIVALENTE, STOCK, STOCK_MIN, ESTADO)
        VALUES (P_NOMBRE, P_DESCRIPCION, P_VALOR_EQUIVALENTE, P_STOCK, ROUND(P_STOCK * 0.1), 'ACTIVO');
        
        COMMIT;
    END SP_CREAR_REGALO;

    -- ASIGNAR REGALO A CLIENTE
    PROCEDURE SP_ASIGNAR_REGALO_CLIENTE(
        P_ID_USUARIO IN NUMBER,
        P_ID_REGALO IN NUMBER,
        P_FECHA_VENCIMIENTO IN DATE DEFAULT NULL,
        P_ID_VENTA IN NUMBER DEFAULT NULL
    ) 
    AS
    BEGIN
        INSERT INTO TA_CLIENTE_REGALOS 
            (ID_USUARIO, ID_REGALO, ID_VENTA, FECHA_VENCIMIENTO, ESTADO)
        VALUES 
            (P_ID_USUARIO, P_ID_REGALO, P_ID_VENTA, P_FECHA_VENCIMIENTO, 'DISPONIBLE');
        
        -- Decrementar stock del regalo
        UPDATE TA_REGALOS SET STOCK = STOCK - 1 WHERE ID_REGALO = P_ID_REGALO;
        
        COMMIT;
    END SP_ASIGNAR_REGALO_CLIENTE;

    -- CANJEAR REGALO
    PROCEDURE SP_CANJEAR_REGALO(
        P_ID_CLIENTE_REGALO IN NUMBER
    ) 
    AS
    BEGIN
        UPDATE TA_CLIENTE_REGALOS 
        SET ESTADO = 'CANJEADO',
            FECHA_CANJE = SYSDATE
        WHERE ID_CLIENTE_REGALO = P_ID_CLIENTE_REGALO;
        
        COMMIT;
    END SP_CANJEAR_REGALO;

    -- LISTAR REGALOS DISPONIBLES DEL CLIENTE
    PROCEDURE SP_LISTAR_REGALOS_CLIENTE(
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                cr.ID_CLIENTE_REGALO, r.NOMBRE, r.DESCRIPCION, r.VALOR_EQUIVALENTE,
                cr.FECHA_OBTENCION, cr.FECHA_VENCIMIENTO, cr.ESTADO, cr.OBSERVACIONES
            FROM TA_CLIENTE_REGALOS cr
            JOIN TA_REGALOS r ON cr.ID_REGALO = r.ID_REGALO
            WHERE cr.ID_USUARIO = P_ID_USUARIO AND cr.ESTADO IN ('DISPONIBLE', 'CANJEADO')
            ORDER BY cr.FECHA_OBTENCION DESC;
    END SP_LISTAR_REGALOS_CLIENTE;

    -- LISTAR TODOS LOS REGALOS
    PROCEDURE SP_LISTAR_REGALOS(
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                ID_REGALO, NOMBRE, DESCRIPCION, VALOR_EQUIVALENTE, STOCK, STOCK_MIN, ESTADO
            FROM TA_REGALOS
            WHERE ESTADO = 'ACTIVO'
            ORDER BY NOMBRE;
    END SP_LISTAR_REGALOS;

END PKG_REGALOS;

-- ========================================
-- PAQUETE PARA MANEJO DE CARRITO
-- ========================================

CREATE OR REPLACE PACKAGE PKG_CARRITO AS
    -- OBTENER O CREAR CARRITO
    PROCEDURE SP_GET_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_ID_CARRITO OUT NUMBER
    );
    
    -- AGREGAR ITEM AL CARRITO
    PROCEDURE SP_AGREGAR_ITEM_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    );
    
    -- ACTUALIZAR CANTIDAD ITEM
    PROCEDURE SP_ACTUALIZAR_ITEM_CARRITO(
        P_ID_CARRITO_ITEM IN NUMBER,
        P_CANTIDAD IN NUMBER
    );
    
    -- ELIMINAR ITEM DEL CARRITO
    PROCEDURE SP_ELIMINAR_ITEM_CARRITO(
        P_ID_CARRITO_ITEM IN NUMBER
    );
    
    -- LISTAR ITEMS DEL CARRITO
    PROCEDURE SP_LISTAR_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- VACIAR CARRITO
    PROCEDURE SP_VACIAR_CARRITO(
        P_ID_USUARIO IN NUMBER
    );
    
END PKG_CARRITO;

CREATE OR REPLACE PACKAGE BODY PKG_CARRITO AS

    -- OBTENER O CREAR CARRITO
    PROCEDURE SP_GET_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_ID_CARRITO OUT NUMBER
    ) 
    AS
    BEGIN
        BEGIN
            SELECT ID_CARRITO INTO P_ID_CARRITO FROM TA_CARRITO WHERE ID_USUARIO = P_ID_USUARIO;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO TA_CARRITO (ID_USUARIO) VALUES (P_ID_USUARIO)
                RETURNING ID_CARRITO INTO P_ID_CARRITO;
                COMMIT;
        END;
    END SP_GET_CARRITO;

    -- AGREGAR ITEM AL CARRITO
    PROCEDURE SP_AGREGAR_ITEM_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    ) 
    AS
        V_ID_CARRITO NUMBER;
        V_PRECIO NUMBER;
    BEGIN
        SP_GET_CARRITO(P_ID_USUARIO, V_ID_CARRITO);
        
        SELECT PRECIO INTO V_PRECIO FROM TA_PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        
        INSERT INTO TA_CARRITO_ITEMS (ID_CARRITO, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
        VALUES (V_ID_CARRITO, P_ID_PRODUCTO, P_CANTIDAD, V_PRECIO);
        
        UPDATE TA_CARRITO SET FECHA_ACTUALIZACION = SYSDATE WHERE ID_CARRITO = V_ID_CARRITO;
        
        COMMIT;
    END SP_AGREGAR_ITEM_CARRITO;

    -- ACTUALIZAR CANTIDAD ITEM
    PROCEDURE SP_ACTUALIZAR_ITEM_CARRITO(
        P_ID_CARRITO_ITEM IN NUMBER,
        P_CANTIDAD IN NUMBER
    ) 
    AS
    BEGIN
        UPDATE TA_CARRITO_ITEMS 
        SET CANTIDAD = P_CANTIDAD
        WHERE ID_CARRITO_ITEM = P_ID_CARRITO_ITEM;
        
        COMMIT;
    END SP_ACTUALIZAR_ITEM_CARRITO;

    -- ELIMINAR ITEM DEL CARRITO
    PROCEDURE SP_ELIMINAR_ITEM_CARRITO(
        P_ID_CARRITO_ITEM IN NUMBER
    ) 
    AS
    BEGIN
        DELETE FROM TA_CARRITO_ITEMS WHERE ID_CARRITO_ITEM = P_ID_CARRITO_ITEM;
        COMMIT;
    END SP_ELIMINAR_ITEM_CARRITO;

    -- LISTAR ITEMS DEL CARRITO
    PROCEDURE SP_LISTAR_CARRITO(
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                ci.ID_CARRITO_ITEM, p.ID_PRODUCTO, p.NOMBRE, p.CODIGO,
                ci.CANTIDAD, ci.PRECIO_UNITARIO, 
                (ci.CANTIDAD * ci.PRECIO_UNITARIO) AS SUBTOTAL,
                p.ESTADO
            FROM TA_CARRITO_ITEMS ci
            JOIN TA_CARRITO c ON ci.ID_CARRITO = c.ID_CARRITO
            JOIN TA_PRODUCTOS p ON ci.ID_PRODUCTO = p.ID_PRODUCTO
            WHERE c.ID_USUARIO = P_ID_USUARIO
            ORDER BY ci.FECHA_AGREGADO;
    END SP_LISTAR_CARRITO;

    -- VACIAR CARRITO
    PROCEDURE SP_VACIAR_CARRITO(
        P_ID_USUARIO IN NUMBER
    ) 
    AS
        V_ID_CARRITO NUMBER;
    BEGIN
        SELECT ID_CARRITO INTO V_ID_CARRITO FROM TA_CARRITO WHERE ID_USUARIO = P_ID_USUARIO;
        
        DELETE FROM TA_CARRITO_ITEMS WHERE ID_CARRITO = V_ID_CARRITO;
        
        UPDATE TA_CARRITO SET FECHA_ACTUALIZACION = SYSDATE WHERE ID_CARRITO = V_ID_CARRITO;
        
        COMMIT;
    END SP_VACIAR_CARRITO;

END PKG_CARRITO;

-- ========================================
-- PAQUETE PARA REPORTES Y ESTADÍSTICAS
-- ========================================

CREATE OR REPLACE PACKAGE PKG_REPORTES AS
    -- VENTAS POR RANGO DE FECHAS
    PROCEDURE SP_VENTAS_POR_FECHAS(
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- PRODUCTOS MÁS VENDIDOS
    PROCEDURE SP_PRODUCTOS_MAS_VENDIDOS(
        P_CANTIDAD_REGISTROS IN NUMBER DEFAULT 10,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- CLIENTES MÁS ACTIVOS
    PROCEDURE SP_CLIENTES_MAS_ACTIVOS(
        P_CANTIDAD_REGISTROS IN NUMBER DEFAULT 10,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- RESUMEN DE VENTAS DIARIAS
    PROCEDURE SP_RESUMEN_VENTAS_DIARIAS(
        P_FECHA IN DATE,
        P_CURSOR OUT SYS_REFCURSOR
    );
    
    -- INVENTARIO BAJO
    PROCEDURE SP_INVENTARIO_BAJO(
        P_CURSOR OUT SYS_REFCURSOR
    );
    
END PKG_REPORTES;

CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS

    -- VENTAS POR RANGO DE FECHAS
    PROCEDURE SP_VENTAS_POR_FECHAS(
        P_FECHA_INICIO IN DATE,
        P_FECHA_FIN IN DATE,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, 
                u.NOMBRE, u.EMAIL,
                v.SUBTOTAL, v.DESCUENTO_TOTAL, v.IMPUESTO, v.TOTAL,
                v.ESTADO_VENTA, v.METODO_PAGO
            FROM TA_VENTAS v
            LEFT JOIN TA_USUARIOS u ON v.ID_USUARIO = u.ID_USUARIO
            WHERE v.FECHA BETWEEN P_FECHA_INICIO AND P_FECHA_FIN
            ORDER BY v.FECHA DESC;
    END SP_VENTAS_POR_FECHAS;

    -- PRODUCTOS MÁS VENDIDOS
    PROCEDURE SP_PRODUCTOS_MAS_VENDIDOS(
        P_CANTIDAD_REGISTROS IN NUMBER DEFAULT 10,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                p.ID_PRODUCTO, p.NOMBRE, p.CODIGO, p.PRECIO,
                SUM(vd.CANTIDAD) AS CANTIDAD_VENDIDA,
                SUM(vd.TOTAL_LINEA) AS INGRESOS_TOTALES
            FROM TA_VENTA_DETALLE vd
            JOIN TA_PRODUCTOS p ON vd.ID_PRODUCTO = p.ID_PRODUCTO
            JOIN TA_VENTAS v ON vd.ID_VENTA = v.ID_VENTA
            WHERE v.ESTADO_VENTA != 'CANCELADA'
            GROUP BY p.ID_PRODUCTO, p.NOMBRE, p.CODIGO, p.PRECIO
            ORDER BY CANTIDAD_VENDIDA DESC
            FETCH FIRST P_CANTIDAD_REGISTROS ROWS ONLY;
    END SP_PRODUCTOS_MAS_VENDIDOS;

    -- CLIENTES MÁS ACTIVOS
    PROCEDURE SP_CLIENTES_MAS_ACTIVOS(
        P_CANTIDAD_REGISTROS IN NUMBER DEFAULT 10,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                u.ID_USUARIO, u.NOMBRE, u.EMAIL, u.TELEFONO,
                COUNT(v.ID_VENTA) AS NUMERO_COMPRAS,
                SUM(v.TOTAL) AS MONTO_TOTAL,
                MAX(v.FECHA) AS ULTIMA_COMPRA
            FROM TA_USUARIOS u
            LEFT JOIN TA_VENTAS v ON u.ID_USUARIO = v.ID_USUARIO
            WHERE u.ESTADO = 'ACTIVO'
            GROUP BY u.ID_USUARIO, u.NOMBRE, u.EMAIL, u.TELEFONO
            HAVING COUNT(v.ID_VENTA) > 0
            ORDER BY MONTO_TOTAL DESC
            FETCH FIRST P_CANTIDAD_REGISTROS ROWS ONLY;
    END SP_CLIENTES_MAS_ACTIVOS;

    -- RESUMEN DE VENTAS DIARIAS
    PROCEDURE SP_RESUMEN_VENTAS_DIARIAS(
        P_FECHA IN DATE,
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                COUNT(ID_VENTA) AS NUMERO_VENTAS,
                SUM(SUBTOTAL) AS SUBTOTAL_DIA,
                SUM(DESCUENTO_TOTAL) AS DESCUENTOS_DIA,
                SUM(IMPUESTO) AS IMPUESTOS_DIA,
                SUM(TOTAL) AS TOTAL_DIA,
                AVG(TOTAL) AS PROMEDIO_VENTA
            FROM TA_VENTAS
            WHERE TRUNC(FECHA) = TRUNC(P_FECHA) AND ESTADO_VENTA != 'CANCELADA';
    END SP_RESUMEN_VENTAS_DIARIAS;

    -- INVENTARIO BAJO
    PROCEDURE SP_INVENTARIO_BAJO(
        P_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT 
                p.ID_PRODUCTO, p.NOMBRE, p.CODIGO, p.PRECIO_COSTO, p.PRECIO,
                i.STOCK, i.STOCK_MIN, i.STOCK_MAX,
                CASE 
                    WHEN i.STOCK <= i.STOCK_MIN THEN 'REORDEN URGENTE'
                    WHEN i.STOCK <= (i.STOCK_MIN * 1.5) THEN 'STOCK BAJO'
                    ELSE 'OK'
                END AS ESTADO_STOCK,
                c.NOMBRE AS CATEGORIA
            FROM TA_INVENTARIO i
            JOIN TA_PRODUCTOS p ON i.ID_PRODUCTO = p.ID_PRODUCTO
            LEFT JOIN TA_CATEGORIAS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
            WHERE i.STOCK <= (i.STOCK_MIN * 1.5) AND p.ESTADO = 'ACTIVO'
            ORDER BY i.STOCK ASC;
    END SP_INVENTARIO_BAJO;

END PKG_REPORTES;
