-- ========================================
-- PROCEDIMIENTOS ALMACENADOS
-- ========================================
-- PAQUETE VENTAS INICIO
CREATE OR REPLACE PACKAGE PKG_VENTAS AS
    -- REGISTRAR VENTA COMPLETA
    PROCEDURE SP_REGISTRAR_VENTA(
        P_ID_USUARIO IN NUMBER,
        P_ID_DIRECCION_ENVIO IN NUMBER,
        P_METODO_PAGO IN VARCHAR2,
        P_VENTA_ID OUT NUMBER
    );
    
    -- AGREGAR DETALLE A VENTA
    PROCEDURE SP_AGREGAR_DETALLE_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    );
    
    -- APLICAR PROMOCIÓN A VENTA
    PROCEDURE SP_APLICAR_PROMOCION(
        P_ID_VENTA IN NUMBER,
        P_ID_PROMOCION IN NUMBER
    );
    
    -- LISTAR VENTAS
    PROCEDURE LISTAR_VENTAS(
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR VENTAS POR USUARIO
    PROCEDURE LISTAR_VENTAS_USUARIO(
        P_ID_USUARIO IN NUMBER,
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR VENTAS DIARIAS
    PROCEDURE VENTAS_DIARIAS(
        VENT_FECHA IN DATE, 
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- ACTUALIZAR ESTADO VENTA
    PROCEDURE ACTUALIZAR_ESTADO_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ESTADO IN VARCHAR2
    );
    
END PKG_VENTAS;

CREATE OR REPLACE PACKAGE BODY PKG_VENTAS AS

    -- REGISTRAR VENTA COMPLETA
    PROCEDURE SP_REGISTRAR_VENTA(
        P_ID_USUARIO IN NUMBER,
        P_ID_DIRECCION_ENVIO IN NUMBER,
        P_METODO_PAGO IN VARCHAR2,
        P_VENTA_ID OUT NUMBER
    ) 
    AS
    BEGIN
        INSERT INTO TA_VENTAS 
            (ID_USUARIO, ID_DIRECCION_ENVIO, METODO_PAGO, SUBTOTAL, TOTAL, ESTADO_VENTA)
        VALUES 
            (P_ID_USUARIO, P_ID_DIRECCION_ENVIO, P_METODO_PAGO, 0, 0, 'PENDIENTE')
        RETURNING ID_VENTA INTO P_VENTA_ID;
        
        COMMIT;
    END SP_REGISTRAR_VENTA;

    -- AGREGAR DETALLE A VENTA
    PROCEDURE SP_AGREGAR_DETALLE_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    ) 
    AS
        V_PRECIO NUMBER;
        V_SUBTOTAL NUMBER;
    BEGIN
        SELECT PRECIO INTO V_PRECIO FROM TA_PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        
        V_SUBTOTAL := V_PRECIO * P_CANTIDAD;
        
        INSERT INTO TA_VENTA_DETALLE 
            (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO, SUBTOTAL, TOTAL_LINEA)
        VALUES 
            (P_ID_VENTA, P_ID_PRODUCTO, P_CANTIDAD, V_PRECIO, V_SUBTOTAL, V_SUBTOTAL);
        
        -- Actualizar total de la venta
        UPDATE TA_VENTAS 
        SET SUBTOTAL = (SELECT SUM(TOTAL_LINEA) FROM TA_VENTA_DETALLE WHERE ID_VENTA = P_ID_VENTA),
            TOTAL = (SELECT SUM(TOTAL_LINEA) FROM TA_VENTA_DETALLE WHERE ID_VENTA = P_ID_VENTA)
        WHERE ID_VENTA = P_ID_VENTA;
        
        -- Actualizar inventario
        UPDATE TA_INVENTARIO SET STOCK = STOCK - P_CANTIDAD WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        
        COMMIT;
    END SP_AGREGAR_DETALLE_VENTA;

    -- APLICAR PROMOCIÓN A VENTA
    PROCEDURE SP_APLICAR_PROMOCION(
        P_ID_VENTA IN NUMBER,
        P_ID_PROMOCION IN NUMBER
    ) 
    AS
        V_DESCUENTO NUMBER;
        V_TIPO VARCHAR2(20);
        V_VALOR NUMBER;
        V_SUBTOTAL NUMBER;
    BEGIN
        SELECT TIPO_DESCUENTO, VALOR_DESCUENTO INTO V_TIPO, V_VALOR 
        FROM TA_PROMOCIONES WHERE ID_PROMOCION = P_ID_PROMOCION;
        
        SELECT SUBTOTAL INTO V_SUBTOTAL FROM TA_VENTAS WHERE ID_VENTA = P_ID_VENTA;
        
        IF V_TIPO = 'PORCENTAJE' THEN
            V_DESCUENTO := V_SUBTOTAL * (V_VALOR / 100);
        ELSE
            V_DESCUENTO := V_VALOR;
        END IF;
        
        INSERT INTO TA_VENTA_PROMOCION (ID_VENTA, ID_PROMOCION, DESCUENTO_APLICADO)
        VALUES (P_ID_VENTA, P_ID_PROMOCION, V_DESCUENTO);
        
        UPDATE TA_VENTAS 
        SET DESCUENTO_TOTAL = DESCUENTO_TOTAL + V_DESCUENTO,
            TOTAL = SUBTOTAL - DESCUENTO_TOTAL - V_DESCUENTO
        WHERE ID_VENTA = P_ID_VENTA;
        
        COMMIT;
    END SP_APLICAR_PROMOCION;

    -- LISTAR VENTAS
    PROCEDURE LISTAR_VENTAS(
        VENT_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.TOTAL, v.ESTADO_VENTA,
                u.NOMBRE, u.EMAIL, u.TELEFONO
            FROM TA_VENTAS v
            LEFT JOIN TA_USUARIOS u ON v.ID_USUARIO = u.ID_USUARIO
            ORDER BY v.FECHA DESC;
    END LISTAR_VENTAS;

    -- LISTAR VENTAS POR USUARIO
    PROCEDURE LISTAR_VENTAS_USUARIO(
        P_ID_USUARIO IN NUMBER,
        VENT_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.SUBTOTAL, v.DESCUENTO_TOTAL, 
                v.IMPUESTO, v.TOTAL, v.ESTADO_VENTA, v.METODO_PAGO
            FROM TA_VENTAS v
            WHERE v.ID_USUARIO = P_ID_USUARIO
            ORDER BY v.FECHA DESC;
    END LISTAR_VENTAS_USUARIO;

    -- LISTAR VENTAS DIARIAS
    PROCEDURE VENTAS_DIARIAS(
        VENT_FECHA IN DATE, 
        VENT_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.TOTAL, v.ESTADO_VENTA,
                u.NOMBRE
            FROM TA_VENTAS v
            LEFT JOIN TA_USUARIOS u ON v.ID_USUARIO = u.ID_USUARIO
            WHERE TRUNC(v.FECHA) = TRUNC(VENT_FECHA)
            ORDER BY v.FECHA;
    END VENTAS_DIARIAS;

    -- ACTUALIZAR ESTADO VENTA
    PROCEDURE ACTUALIZAR_ESTADO_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ESTADO IN VARCHAR2
    )
    AS
    BEGIN
        UPDATE TA_VENTAS 
        SET ESTADO_VENTA = P_ESTADO,
            FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_VENTA = P_ID_VENTA;
        
        COMMIT;
    END ACTUALIZAR_ESTADO_VENTA;

END PKG_VENTAS;