-- ========================================
-- PROCEDIMIENTOS ALMACENADOS
-- ========================================
-- PAQUETE USUARIO INICIO
CREATE OR REPLACE PACKAGE PKG_USUARIOS AS
    -- CREAR USUARIO
    PROCEDURE CREAR_USUARIO(
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_USUARIO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_ID_ROL IN NUMBER
    );
    
    -- ACTUALIZAR DATOS PERSONALES
    PROCEDURE UPDATE_USUARIO(
        USER_ID IN NUMBER,
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2
    );
    
    -- ACTUALIZAR ACCESO USUARIO
    PROCEDURE UPDATE_USUARIO_ACCESO(
        USER_ID IN NUMBER,
        USER_USUARIO IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_ESTADO IN VARCHAR2
    );
    
    -- LISTAR TODOS LOS USUARIOS
    PROCEDURE LISTAR_USUARIOS(
        USER_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR USUARIO POR ID
    PROCEDURE LISTAR_USUARIOS_ID(
        USER_ID IN NUMBER,
        USER_CURSOR OUT SYS_REFCURSOR
    );
    
    -- CAMBIAR ROL DE USUARIO
    PROCEDURE CAMBIAR_ROL_USUARIO(
        USER_ID IN NUMBER,
        USER_ID_ROL IN NUMBER
    );
    
END PKG_USUARIOS;

CREATE OR REPLACE PACKAGE BODY PKG_USUARIOS AS

    -- CREAR USUARIO
    PROCEDURE CREAR_USUARIO(
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_USUARIO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_ID_ROL IN NUMBER,
        USER_MODIFICACION IN VARCHAR2
    ) 
    AS
    BEGIN
        INSERT INTO TA_USUARIOS 
            (NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NACIMIENTO, TELEFONO, USUARIO, EMAIL, PASSWORD_HASH, ESTADO, ID_ROL, USUARIO_ACTUALIZACION)
        VALUES 
            (USER_NOMBRE, USER_PATERNO, USER_MATERNO, USER_FECHA_NAC, USER_TELEFONO, USER_USUARIO, USER_EMAIL, USER_PASSWORD, 'ACTIVO', USER_ID_ROL, USER);
        
        COMMIT;
    END CREAR_USUARIO;

    -- ACTUALIZAR DATOS PERSONALES
    PROCEDURE UPDATE_USUARIO(
        USER_ID IN NUMBER,
        USER_NOMBRE IN VARCHAR2,
        USER_PATERNO IN VARCHAR2,
        USER_MATERNO IN VARCHAR2,
        USER_FECHA_NAC IN DATE,
        USER_TELEFONO IN VARCHAR2,
        USER_EMAIL IN VARCHAR2
    ) 
    AS
    BEGIN
        UPDATE TA_USUARIOS SET NOMBRE = USER_NOMBRE, AP_PATERNO = USER_PATERNO, AP_MATERNO = USER_MATERNO, FECHA_NACIMIENTO = USER_FECHA_NAC, 
            TELEFONO = USER_TELEFONO, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END UPDATE_USUARIO;

        -- ACTUALIZAR ACCESO USUARIO
    PROCEDURE UPDATE_USUARIO_ACCESO(
        USER_ID IN NUMBER,
        USER_USUARIO IN VARCHAR2,
        USER_PASSWORD IN VARCHAR2,
        USER_EMAIL IN VARCHAR2,
        USER_ESTADO IN VARCHAR2
    )
    AS
    BEGIN
        UPDATE TA_USUARIOS SET USUARIO = USER_USUARIO, PASSWORD_HASH = USER_PASSWORD, ESTADO = USER_ESTADO, 
        	EMAIL = USER_EMAIL, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END UPDATE_USUARIO_ACCESO;

           -- LISTAR TODOS LOS USUARIOS
    PROCEDURE LISTAR_USUARIOS(
        USER_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN USER_CURSOR FOR
            SELECT U.ID_USUARIO, U.NOMBRE, U.AP_PATERNO, U.AP_MATERNO, U.FECHA_NACIMIENTO, U.TELEFONO, U.EMAIL, U.USUARIO,
                R.NOMBRE_ROL, U.ESTADO, U.FECHA_CREACION
            FROM TA_USUARIOS U
            LEFT JOIN TA_ROLES R ON U.ID_ROL = R.ID_ROL
            ORDER BY U.ID_USUARIO;
    END LISTAR_USUARIOS;
    
    -- LISTAR USUARIO POR ID
    PROCEDURE LISTAR_USUARIOS_ID(
        USER_ID IN NUMBER,
        USER_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN USER_CURSOR FOR
            SELECT 
                U.ID_USUARIO, U.NOMBRE, U.AP_PATERNO, U.AP_MATERNO, U.FECHA_NACIMIENTO, U.TELEFONO, U.EMAIL, U.USUARIO, 
                R.NOMBRE_ROL, U.ESTADO, U.FECHA_CREACION
            FROM TA_USUARIOS U
            LEFT JOIN TA_ROLES R ON U.ID_ROL = R.ID_ROL
            WHERE U.ID_USUARIO = USER_ID;
    END LISTAR_USUARIOS_ID;
    
    -- CAMBIAR ROL DE USUARIO
    PROCEDURE CAMBIAR_ROL_USUARIO(
        USER_ID IN NUMBER,
        USER_ID_ROL IN NUMBER
    )
    AS
    BEGIN
        UPDATE TA_USUARIOS SET ID_ROL = USER_ID_ROL, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_USUARIO = USER_ID;
        
        COMMIT;
    END CAMBIAR_ROL_USUARIO;

END PKG_USUARIOS;
--PAQUETE USUARIO FINAL


-- PAQUETE PRODUCTOS INICIO
CREATE OR REPLACE PACKAGE PKG_PRODUCTOS AS
  -- GUARDAR PRODUCTO
    PROCEDURE SP_INSERT_PRODUCTO(
        PROD_ID_CATEGORIA IN NUMBER,
        PROD_ID_MARCA IN NUMBER,
        PROD_ID_PROVEEDOR IN NUMBER,
        PROD_DESCRIPCION IN VARCHAR2,
        PROD_CODIGO IN VARCHAR2,
        PROD_NOMBRE IN VARCHAR2,
        PROD_PRECIO IN NUMBER,
        PROD_PRECIO_COSTO IN NUMBER,
        PROD_STOCK IN NUMBER
    );
    
    -- ACTUALIZAR PRODUCTO
    PROCEDURE SP_UPDATE_PRODUCTO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_NOMBRE IN VARCHAR2,
        PROD_PRECIO IN NUMBER,
        PROD_DESCRIPCION IN VARCHAR2,
        PROD_ESTADO IN VARCHAR2,
        PROD_MOTIVO IN VARCHAR2
    );
    
    -- ELIMINAR PRODUCTO - ELIMINACIÓN LÓGICA
    PROCEDURE SP_DELETE_PRODUCTO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_ESTADO IN VARCHAR2
    );
    
    -- OBTENER PRODUCTO POR ID
    PROCEDURE SP_GET_PRODUCTO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_CURSOR OUT SYS_REFCURSOR
    );
    
    -- OBTENER TODOS LOS PRODUCTOS
    PROCEDURE SP_OBTENER_PRODUCTOS(
    	PROD_ESTADO IN VARCHAR2,
        PROD_CURSOR OUT SYS_REFCURSOR
    );
   
    
END PKG_PRODUCTOS;

CREATE OR REPLACE PACKAGE BODY PKG_PRODUCTOS AS

    	-- GUARDAR PRODUCTO
    PROCEDURE SP_INSERT_PRODUCTO(
        PROD_ID_CATEGORIA IN NUMBER,
        PROD_ID_MARCA IN NUMBER,
        PROD_ID_PROVEEDOR IN NUMBER,
        PROD_DESCRIPCION IN VARCHAR2,
        PROD_CODIGO IN VARCHAR2,
        PROD_NOMBRE IN VARCHAR2,
        PROD_PRECIO IN NUMBER,
        PROD_PRECIO_COSTO IN NUMBER,
        PROD_STOCK IN NUMBER
    ) 
    AS
        V_ID_PRODUCTO NUMBER;
    BEGIN
        INSERT INTO TA_PRODUCTOS 
            (ID_CATEGORIA, ID_MARCA, ID_PROVEEDOR, DESCRIPCION, CODIGO, NOMBRE, PRECIO, PRECIO_COSTO, ESTADO, USUARIO_ACTUALIZACION)
        VALUES 
            (PROD_ID_CATEGORIA, PROD_ID_MARCA, PROD_ID_PROVEEDOR, PROD_DESCRIPCION, PROD_CODIGO, PROD_NOMBRE, PROD_PRECIO, PROD_PRECIO_COSTO, 'ACTIVO', USER)
        
            RETURNING ID_PRODUCTO INTO V_ID_PRODUCTO;

        INSERT INTO TA_INVENTARIO (ID_PRODUCTO, STOCK, STOCK_MIN)
        VALUES (V_ID_PRODUCTO, PROD_STOCK, PROD_STOCK * 0.2); -- Stock mínimo al 20%

        COMMIT;
        
    END SP_INSERT_PRODUCTO;
    
     -- ACTUALIZAR PRODUCTO
    PROCEDURE SP_UPDATE_PRODUCTO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_NOMBRE IN VARCHAR2,
        PROD_PRECIO IN NUMBER,
        PROD_DESCRIPCION IN VARCHAR2,
        PROD_ESTADO IN VARCHAR2,
        PROD_MOTIVO IN VARCHAR2
    ) 
    AS
        V_PRECIO_ANTERIOR NUMBER;
    BEGIN
        -- Guardar precio anterior en historial
        SELECT PRECIO INTO V_PRECIO_ANTERIOR FROM TA_PRODUCTOS WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;
        
        IF V_PRECIO_ANTERIOR != PROD_PRECIO THEN
            INSERT INTO TA_HISTORIAL_PRECIOS 
                (ID_PRODUCTO, PRECIO_ANTERIOR, PRECIO_NUEVO, USUARIO_CAMBIO, MOTIVO)
            VALUES 
                (PROD_ID_PRODUCTO, V_PRECIO_ANTERIOR, PROD_PRECIO, USER, PROD_MOTIVO);
        END IF;
        
        UPDATE TA_PRODUCTOS SET NOMBRE = PROD_NOMBRE, PRECIO = PROD_PRECIO, DESCRIPCION = PROD_DESCRIPCION, ESTADO = PROD_ESTADO, 
           FECHA_ACTUALIZACION = SYSDATE, USUARIO_ACTUALIZACION = USER
        WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;

        COMMIT;
    END SP_UPDATE_PRODUCTO;
    
   -- ELIMINAR PRODUCTO - ELIMINACIÓN LÓGICA     
   PROCEDURE SP_DELETE_PRODUCTO(
        	PROD_ID_PRODUCTO IN NUMBER,
        	PROD_ESTADO IN VARCHAR2
        ) 
    AS
    BEGIN
        UPDATE TA_PRODUCTOS SET ESTADO = PROD_ESTADO, FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_PRODUCTO = PROD_ID_PRODUCTO;

        COMMIT;
    END SP_DELETE_PRODUCTO;    
    
    -- OBTENER PRODUCTO POR ID
    PROCEDURE SP_GET_PRODUCTO(
        PROD_ID_PRODUCTO IN NUMBER,
        PROD_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN PROD_CURSOR FOR
            SELECT P.ID_PRODUCTO, P.NOMBRE, P.DESCRIPCION, P.CODIGO, P.PRECIO, P.PRECIO_COSTO,
                P.ESTADO, C.NOMBRE AS CATEGORIA, M.NOMBRE AS MARCA, 
                PV.NOMBRE AS PROVEEDOR, I.STOCK, I.STOCK_MIN
            FROM TA_PRODUCTOS P
            LEFT JOIN TA_CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
            LEFT JOIN TA_MARCAS M ON P.ID_MARCA = M.ID_MARCA
            LEFT JOIN TA_PROVEEDORES PV ON P.ID_PROVEEDOR = PV.ID_PROVEEDOR
            LEFT JOIN TA_INVENTARIO I ON P.ID_PRODUCTO = I.ID_PRODUCTO
            WHERE P.ID_PRODUCTO = PROD_ID_PRODUCTO;
    
    END SP_GET_PRODUCTO;
        
    
    -- OBTENER TODOS LOS PRODUCTOS
    PROCEDURE SP_OBTENER_PRODUCTOS(
    	PROD_ESTADO IN VARCHAR2,
    	PROD_CURSOR OUT SYS_REFCURSOR
    	) 
    AS
    BEGIN
        OPEN PROD_CURSOR FOR
            SELECT 
                P.ID_PRODUCTO, P.NOMBRE, P.DESCRIPCION, P.CODIGO, P.PRECIO, P.PRECIO_COSTO,
                P.ESTADO, C.NOMBRE AS CATEGORIA, M.NOMBRE AS MARCA, 
                PV.NOMBRE AS PROVEEDOR, I.STOCK, I.STOCK_MIN
            FROM TA_PRODUCTOS P
            LEFT JOIN TA_CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
            LEFT JOIN TA_MARCAS M ON P.ID_MARCA = M.ID_MARCA
            LEFT JOIN TA_PROVEEDORES PV ON P.ID_PROVEEDOR = PV.ID_PROVEEDOR
            LEFT JOIN TA_INVENTARIO I ON P.ID_PRODUCTO = I.ID_PRODUCTO
            WHERE P.ESTADO = PROD_ESTADO
            ORDER BY P.ID_PRODUCTO;
    END SP_OBTENER_PRODUCTOS;

END PKG_PRODUCTOS;
--PAQUETE PRODUCTOS FIN

-- PAQUETE VENTAS INICIO
CREATE OR REPLACE PACKAGE PKG_VENTAS AS
    -- REGISTRAR VENTA COMPLETA
    PROCEDURE SP_REGISTRAR_VENTA(
        P_ID_USUARIO IN NUMBER,
        P_ID_DIRECCION_ENVIO IN NUMBER,
        P_METODO_PAGO IN VARCHAR2,
        P_VENTA_ID OUT NUMBER
    );
    
    -- AGREGAR DETALLE A VENTA
    PROCEDURE SP_AGREGAR_DETALLE_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    );
    
    -- APLICAR PROMOCIÓN A VENTA
    PROCEDURE SP_APLICAR_PROMOCION(
        P_ID_VENTA IN NUMBER,
        P_ID_PROMOCION IN NUMBER
    );
    
    -- LISTAR VENTAS
    PROCEDURE LISTAR_VENTAS(
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR VENTAS POR USUARIO
    PROCEDURE LISTAR_VENTAS_USUARIO(
        P_ID_USUARIO IN NUMBER,
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- LISTAR VENTAS DIARIAS
    PROCEDURE VENTAS_DIARIAS(
        VENT_FECHA IN DATE, 
        VENT_CURSOR OUT SYS_REFCURSOR
    );
    
    -- ACTUALIZAR ESTADO VENTA
    PROCEDURE ACTUALIZAR_ESTADO_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ESTADO IN VARCHAR2
    );
    
END PKG_VENTAS;

CREATE OR REPLACE PACKAGE BODY PKG_VENTAS AS

    -- REGISTRAR VENTA COMPLETA
    PROCEDURE SP_REGISTRAR_VENTA(
        P_ID_USUARIO IN NUMBER,
        P_ID_DIRECCION_ENVIO IN NUMBER,
        P_METODO_PAGO IN VARCHAR2,
        P_VENTA_ID OUT NUMBER
    ) 
    AS
    BEGIN
        INSERT INTO TA_VENTAS 
            (ID_USUARIO, ID_DIRECCION_ENVIO, METODO_PAGO, SUBTOTAL, TOTAL, ESTADO_VENTA)
        VALUES 
            (P_ID_USUARIO, P_ID_DIRECCION_ENVIO, P_METODO_PAGO, 0, 0, 'PENDIENTE')
        RETURNING ID_VENTA INTO P_VENTA_ID;
        
        COMMIT;
    END SP_REGISTRAR_VENTA;

    -- AGREGAR DETALLE A VENTA
    PROCEDURE SP_AGREGAR_DETALLE_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ID_PRODUCTO IN NUMBER,
        P_CANTIDAD IN NUMBER
    ) 
    AS
        V_PRECIO NUMBER;
        V_SUBTOTAL NUMBER;
    BEGIN
        SELECT PRECIO INTO V_PRECIO FROM TA_PRODUCTOS WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        
        V_SUBTOTAL := V_PRECIO * P_CANTIDAD;
        
        INSERT INTO TA_VENTA_DETALLE 
            (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO, SUBTOTAL, TOTAL_LINEA)
        VALUES 
            (P_ID_VENTA, P_ID_PRODUCTO, P_CANTIDAD, V_PRECIO, V_SUBTOTAL, V_SUBTOTAL);
        
        -- Actualizar total de la venta
        UPDATE TA_VENTAS 
        SET SUBTOTAL = (SELECT SUM(TOTAL_LINEA) FROM TA_VENTA_DETALLE WHERE ID_VENTA = P_ID_VENTA),
            TOTAL = (SELECT SUM(TOTAL_LINEA) FROM TA_VENTA_DETALLE WHERE ID_VENTA = P_ID_VENTA)
        WHERE ID_VENTA = P_ID_VENTA;
        
        -- Actualizar inventario
        UPDATE TA_INVENTARIO SET STOCK = STOCK - P_CANTIDAD WHERE ID_PRODUCTO = P_ID_PRODUCTO;
        
        COMMIT;
    END SP_AGREGAR_DETALLE_VENTA;

    -- APLICAR PROMOCIÓN A VENTA
    PROCEDURE SP_APLICAR_PROMOCION(
        P_ID_VENTA IN NUMBER,
        P_ID_PROMOCION IN NUMBER
    ) 
    AS
        V_DESCUENTO NUMBER;
        V_TIPO VARCHAR2(20);
        V_VALOR NUMBER;
        V_SUBTOTAL NUMBER;
    BEGIN
        SELECT TIPO_DESCUENTO, VALOR_DESCUENTO INTO V_TIPO, V_VALOR 
        FROM TA_PROMOCIONES WHERE ID_PROMOCION = P_ID_PROMOCION;
        
        SELECT SUBTOTAL INTO V_SUBTOTAL FROM TA_VENTAS WHERE ID_VENTA = P_ID_VENTA;
        
        IF V_TIPO = 'PORCENTAJE' THEN
            V_DESCUENTO := V_SUBTOTAL * (V_VALOR / 100);
        ELSE
            V_DESCUENTO := V_VALOR;
        END IF;
        
        INSERT INTO TA_VENTA_PROMOCION (ID_VENTA, ID_PROMOCION, DESCUENTO_APLICADO)
        VALUES (P_ID_VENTA, P_ID_PROMOCION, V_DESCUENTO);
        
        UPDATE TA_VENTAS 
        SET DESCUENTO_TOTAL = DESCUENTO_TOTAL + V_DESCUENTO,
            TOTAL = SUBTOTAL - DESCUENTO_TOTAL - V_DESCUENTO
        WHERE ID_VENTA = P_ID_VENTA;
        
        COMMIT;
    END SP_APLICAR_PROMOCION;

    -- LISTAR VENTAS
    PROCEDURE LISTAR_VENTAS(
        VENT_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.TOTAL, v.ESTADO_VENTA,
                u.NOMBRE, u.EMAIL, u.TELEFONO
            FROM TA_VENTAS v
            LEFT JOIN TA_USUARIOS u ON v.ID_USUARIO = u.ID_USUARIO
            ORDER BY v.FECHA DESC;
    END LISTAR_VENTAS;

    -- LISTAR VENTAS POR USUARIO
    PROCEDURE LISTAR_VENTAS_USUARIO(
        P_ID_USUARIO IN NUMBER,
        VENT_CURSOR OUT SYS_REFCURSOR
    ) 
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.SUBTOTAL, v.DESCUENTO_TOTAL, 
                v.IMPUESTO, v.TOTAL, v.ESTADO_VENTA, v.METODO_PAGO
            FROM TA_VENTAS v
            WHERE v.ID_USUARIO = P_ID_USUARIO
            ORDER BY v.FECHA DESC;
    END LISTAR_VENTAS_USUARIO;

    -- LISTAR VENTAS DIARIAS
    PROCEDURE VENTAS_DIARIAS(
        VENT_FECHA IN DATE, 
        VENT_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN VENT_CURSOR FOR
            SELECT 
                v.ID_VENTA, v.NUMERO_PEDIDO, v.FECHA, v.TOTAL, v.ESTADO_VENTA,
                u.NOMBRE
            FROM TA_VENTAS v
            LEFT JOIN TA_USUARIOS u ON v.ID_USUARIO = u.ID_USUARIO
            WHERE TRUNC(v.FECHA) = TRUNC(VENT_FECHA)
            ORDER BY v.FECHA;
    END VENTAS_DIARIAS;

    -- ACTUALIZAR ESTADO VENTA
    PROCEDURE ACTUALIZAR_ESTADO_VENTA(
        P_ID_VENTA IN NUMBER,
        P_ESTADO IN VARCHAR2
    )
    AS
    BEGIN
        UPDATE TA_VENTAS 
        SET ESTADO_VENTA = P_ESTADO,
            FECHA_ACTUALIZACION = SYSDATE
        WHERE ID_VENTA = P_ID_VENTA;
        
        COMMIT;
    END ACTUALIZAR_ESTADO_VENTA;

END PKG_VENTAS;